### ISSUE TITLE
Collecting output for an array of glob patterns based on inputs fails

### ISSUE THREAD

**Issue by biokcb** [IBMSpectrumComputing/cwlexec#14]
Hi,

We have a simple example that takes a string as input and outputs two files with names based on the input string. When using glob to find both files based on the name pattern `$(inputs.name)_1.txt` and `$(inputs.name)_2.txt`, the glob seems to interpret these as literal strings rather than evaluating `$(inputs.name)` in each case:

**outfile.txt**
```
182   "outputBinding" : {
183     "glob" : {
184       "patterns" : [ "$(inputs.name)_1.txt", "$(inputs.name)_2.txt" ],
```

then returns:
```
218 {
219   "out_file" : [ ]
220 }
```

If `$(inputs.name)` is changed to the exact string, it works, but it should evaluate these for pattern matching. 

[GlobOutputArrayError.tar.gz](https://github.com/IBMSpectrumComputing/cwlexec/files/2181903/GlobOutputArrayError.tar.gz)

**Comment by skeeey** [comment]
Yes, the pattern expression is not handled, fixed at 4fedf26
