### ISSUE TITLE
Optional array workflow input does not use tool's default value

### ISSUE THREAD

**Issue by biokcb** [IBMSpectrumComputing/cwlexec#19]
Hi,

We have a simple example workflow (`foo_wf.cwl`) that takes an optional `string` array as input. It calls `foo.cwl` which sets a default for the input array. This workflow works when given the string array as input, but when given no inputs it throws the following error in `errfile.txt`:

`com.ibm.spectrumcomputing.cwl.model.process.parameter.type.NullValue cannot be cast to java.util.List`

This only happens at the workflow level with the optional array input. I believe since it is optional for the workflow, it should return `null` as input to the step calling `foo.cwl` where it then uses the default array for the command line tool input because the input is null. This is the behavior for a non-array optional input. 

[OptionalArrayInputError.tar.gz](https://github.com/IBMSpectrumComputing/cwlexec/files/2207162/OptionalArrayInputError.tar.gz)

**Comment by skeeey** [comment]
This is bug, it fails to case a CWL `NULL` value to list see 9b15b52
