### ISSUE TITLE
Fails to run when input CWLType is an array of File, Directory

### ISSUE THREAD

**Issue by biokcb** [IBMSpectrumComputing/cwlexec#23]
Hi,

We have a simple tool (attached) that performs `echo` on an input, and accepts either a File or Directory. When we run it, it returns the error `too many types for one paramter` . I've tested this with an array that is [File, string] or [Directory, string] or [string, int] and it seems to work, but the combination of [File, Directory] throws this error. 

[TooManyTypesError.tar.gz](https://github.com/IBMSpectrumComputing/cwlexec/files/2258933/TooManyTypesError.tar.gz)

**Comment by skeeey** [comment]
The root cause is we did not distinguish File and Directory, we should use `class` field to distinguish them

**Comment by skeeey** [comment]
Fixed at 7587f60
