### ISSUE TITLE
ExpressionTool cannot access input directory listing files

### ISSUE THREAD

**Issue by biokcb** [IBMSpectrumComputing/cwlexec#24]
Hi,

I have a simple ExpressionTool (attached) I wanted to test with the recently added feature. It takes in a directory as input and return's the directory's listing as a file array. However, I get an error when running this that states 

`09:54:43.736 default [pool-4-thread-1] ERROR c.i.s.c.e.e.lsf.LSFWorkflowRunner - Failed to capture output for job (directory_to_files): The file "/home/kbrown1/ExpressionToolDirectoryError/workdir/1bd21483-9530-48e9-bc2c-f7d129b428e9/2.tmp" cannot be accessed.`

It also exits with exit code 0 instead of a non-zero exit code, but returns no output. 

As far as I can tell it seems to be an issue with the input directory listing. I tested swapping the `listing` attribute for `basename` to simple return a `string` of the directory's name and this worked successfully. It seems to know what outputs to collect, just can't actually collect them. 

[ExpressionToolDirectoryError.tar.gz](https://github.com/IBMSpectrumComputing/cwlexec/files/2259561/ExpressionToolDirectoryError.tar.gz)

**Comment by biokcb** [comment]
As an additional note - going in the reverse direction using a `File[]` as input and turning it into the `listing` attribute of a new directory works fine.

**Comment by skeeey** [comment]
Fixed at b1631c9
