### ISSUE TITLE
coresMin used instead of ramMin

### ISSUE THREAD

**Issue by biokcb** [IBMSpectrumComputing/cwlexec#26]
Hi,

We were testing using the ResourceRequirement field in the CWL document and noticed that when using ramMin the sub command submits `-R mem>coresMin`

Looks like the error is likely simply fixed here by replacing coresMin with ramMin: https://github.com/IBMSpectrumComputing/cwlexec/blob/e3c19121ac9ec8db24f09c542931345a43bb4ef0/src/main/java/com/ibm/spectrumcomputing/cwl/exec/service/CWLLSFCommandServiceImpl.java#L177

Attached is a test case. Even though ramMin is set to 100, it uses coresMin (either the given value or null if it is not given where it produces an error).

[ramMinError.tar.gz](https://github.com/IBMSpectrumComputing/cwlexec/files/2275467/ramMinError.tar.gz)

**Comment by skeeey** [comment]
Oh, it is an obvious error :-), has fixed at 6bbb51d
