### ISSUE TITLE
Cannot use Array type with inputs

### ISSUE THREAD

**Issue by drjrm3** [IBMSpectrumComputing/cwlexec#29]
For tools which require a flag before each item in an array we can use the methods described in [The array-inputs tutorial](https://www.commonwl.org/user_guide/09-array-inputs/). This works well for cwltool, but does not seem to get passed to the baseCommand in cwlexec.

Attached is an example command 'foo' which takes multiple `--INPUT` files and cats them all to a single `--OUTPUT` file. With cwltool it works but with cwlexec it does not pass any of the `--INPUT` flags.

[MultiInputError.tar.gz](https://github.com/IBMSpectrumComputing/cwlexec/files/2407011/MultiInputError.tar.gz)

**Comment by skeeey** [comment]
This should be a bug, we will work on it

**Comment by skeeey** [comment]
Fixed at 4485b0b
