### ISSUE TITLE
path provided, yet "The field [path, location or contents] is required."

### ISSUE THREAD

**Issue by mr-c** [IBMSpectrumComputing/cwlexec#3]
https://ci.commonwl.org/job/cwlexec/8/testReport/conformance_test_v1/0/Test_dynamic_resource_reqs_referencing_the_size_of_Files_inside_a_Directory/

From a new conformance test: 
https://github.com/common-workflow-language/common-workflow-language/pull/690/files

**Comment by mr-c** [comment]
Maybe the error is due to the `Directory` literal? https://github.com/common-workflow-language/common-workflow-language/pull/690/files#diff-ce2c77e84e9e514f9769b40221fc81d6R3

**Comment by PlatformLSF** [comment]
We used same way to parse the CWL file and directory, but, follow the specification, they are different, especially, when the path or location is not defined, for file, we should check contents, and for directory, we should check listing. Now we corrected them, see fa4962f
