### ISSUE TITLE
Bad Scatter in subworkflow

### ISSUE THREAD

**Issue by drjrm3** [IBMSpectrumComputing/cwlexec#33]
I have a CommandLineTool (foo.cwl), Workflow (inner.cwl) which calls foo.cwl, and another workflow (outter.cwl) which scatters over inner.cwl. Both foo.cwl and inner.cwl work as intended, but outter.cwl does not properly scatter over inner.cwl. That is, instead of scattering over the 'input_file' as it should, it simply calls 'foo' with all possible 'input_file's as input.

It should be:

`foo --INPUT file1.txt`
`foo --INPUT file2.txt`

but instead, it invokes `foo` as

`foo --INPUT file1.txt file2.txt`

This may be related to [issue 20](https://github.com/IBMSpectrumComputing/cwlexec/issues/20) which I saw was recently moved to 'enhancement' rather than 'known issue'. In either case I'm hoping we will be able to scatter over subworkflows in this way as it will be very useful for our pipelines.

In the attached 'BadScatter.tar.gz' you will see that '01_foo.sh' gives the expected output, '02_inner.sh' gives the expected output, but '03_outer.sh' fails and that the invocation is a single call to `foo` with all possible input files, though the intent is for them to be scatter over as described above.

[BadScatter.tar.gz](https://github.com/IBMSpectrumComputing/cwlexec/files/2447265/BadScatter.tar.gz)

**Comment by skeeey** [comment]
@drjrm3, yes, this is related to #20. Currently, the `cwlexec` will ignore the `sactter` attribute in subflow and treat the subflow as a single flow to run.

As you know, we plan to fix this problem at #20, so I close this problem and trace this problem at #20

**Comment by drjrm3** [comment]
Thank you for verifying this is the same issue. In the mean time I will try to use the workaround proposed for #20.
