### ISSUE TITLE
Failed to evaluate the expression in the [std] field, string is required

### ISSUE THREAD

**Issue by drjrm3** [IBMSpectrumComputing/cwlexec#37]
The fix for #36 resolved that issue but now I am running into an issue when I try to redirect stdout to a file within the CommandLineTool being scattered over. I have modified that example to show that the first step seems to succeed, but the second step fails with 

```
Failed to evaluate the expression "$(inputs.output_file)" in the [std] field, string is required.
```
[UndefinedVariableError2.tar.gz](https://github.com/IBMSpectrumComputing/cwlexec/files/2543354/UndefinedVariableError2.tar.gz)

**Comment by skeeey** [comment]
@drjrm3 Can you upload your tar file again?

**Comment by skeeey** [comment]
And follow the  CWL specification, the `std` field should be a `string` or `expression`, so we require the `expression` return a `string` value, can you try to make the `$(inputs.output_file)` returns a string? e.g. `$(inputs.output_file.rootname)` or something.

**Comment by skeeey** [comment]
This problem related to #36, currently,  we put off the `output_file` evaluation on its upper level, so we also need to put off this evaluation, it means we need evaluate this expression after `output_file` evaluation is done. I will try to fix this issue

**Comment by skeeey** [comment]
@drjrm3 I fixed this problem, but you may forget to handle the `OUTPUT_FILE` in `process_reads.sh` in your uploaded package.
