### ISSUE TITLE
Incorrect Null evaluation of file

### ISSUE THREAD

**Issue by drjrm3** [IBMSpectrumComputing/cwlexec#38]
#37 seems to be resolved now with my minimal example but when I ran my larger workflow again it still failed. After dissecting each piece I found that an unrelated parameter seems to be causing this same error.

When I change the example CLT / WF from #37 and allow the CLT to have an optional `boolean` and then edit the WF to interpret the boolean as `z: {valueFrom: $(true)}` I get the same `std` error I did in #37. However, the new `z` parameter is (I think) completely unrelated to the parameter involved with the `std` error.

[UndefinedVariableError2.5.tar.gz](https://github.com/IBMSpectrumComputing/cwlexec/files/2570011/UndefinedVariableError2.5.tar.gz)

**Comment by skeeey** [comment]
This is because I evaluate the `stdout/stderr` at a wrong phase, I should evaluate them after the inputs  were handled
