### ISSUE TITLE
$(inputs.other_file.nameroot) evaluates to Null upon file scatter

### ISSUE THREAD

**Issue by drjrm3** [IBMSpectrumComputing/cwlexec#6]
We have a simple example where we are trying to concatenate `english.txt` with `french.txt`, `german.txt`, and `spanish.txt` via scatter using `$(inputs.other_file.nameroot)` in the CommandLineTool being scattered. This works as desired in cwltool, but in CWLEXEC, we get no output files and the following information in debug mode (found also in the 'outfile.txt', attached):

`16:15:47.191 default [main] DEBUG c.i.s.c.e.util.evaluator.JSEvaluator - Evaluated js expression "$(inputs.other_file.nameroot)" to A null object`

[NullJSObjectError.tar.gz](https://github.com/IBMSpectrumComputing/cwlexec/files/2060128/NullJSObjectError.tar.gz)

**Comment by PlatformLSF** [comment]
This issue has the same reason with #7
